---  # default config

# EXCHANGE (Select which exchange you want to run Corecito on. Possible values -> 'crypto.com' or 'binance')
corecito_exchange: crypto.com

# API
api_key: <your Crypto.com Exchange or Binance API key here>
api_secret: <your Crypto.com Exchange or Binance API secret here>

# CORE NUMBER SETTINGS
core_number: 2 # EUR, ETH, etc...
# These min and max price_stops are useful to stop corecito from selling or buying all your assets after many small deviations. Un/comment to enable/disable them.
#min_price_stop: 0.01 # Minimum price at which it stops making transactions.
#max_price_stop: 0.05 # Maximum price at which it stops making transactions.
min_core_number_increase_percentage: 3
max_core_number_increase_percentage: 10
min_core_number_decrease_percentage: 3
max_core_number_decrease_percentage: 10

# EXCHANGE SETTINGS
cryptocom_trading_pair: ETH_BTC # This must be one of the pairs listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/pairs.py
cryptocom_core_number_currency: ETH # this must be one of the currencies listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/coins.py
cryptocom_base_currency: BTC # this must be one of the currencies listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/coins.py
cryptocom_max_decimals_buy: 6 # This is the limit Crypto.com has on ETH_BTC pair https://crypto.com/exchange/trade/spot/ETH_BTC
cryptocom_max_decimals_sell: 3
binance_trading_pair: ETHBTC # This must be one of the pairs listed in Binance
binance_core_number_currency: ETH # # This must be one of the coins listed in Binance
binance_base_currency: BTC # # This must be one of the coins listed in Binance
binance_max_decimals_buy: 6
binance_max_decimals_sell: 6

# FIAT SETTINGS
is_fiat: False  # True  => If a trading pair involving Fiat or Stable Coins is used.  i.e. BTC/EUR, ETH/USDT, etc...
                # False => If a trading pair involving two crypto currencies is used. i.e. BTC/ETH, ADA/ETH, etc...

# CORECITO MODES
safe_mode_on: True # True => no real trades will be made; False => real trades will be made
test_mode_on: True # (True => Corecito will run just once ; False => Corecito will run forever until stopped)

# LOOP SETTINGS
seconds_between_iterations: 5

# TELEGRAM CONFIGURATION
telegram_notifications_on: False # must be True or False
telegram_bot_token: <bot token>
telegram_user_id: <your user id> # In telegram app, search for '@userinfobot' and tap 'Start', it will reply with your user_id
